"use client";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EntitySidebar } from "./EntitySidebar";
import { TimeGrid } from "./TimeGrid";
import { useState, useEffect, useTransition } from "react";
import { useTranslations } from "next-intl";
import { ScheduleSlotDialog } from "./ScheduleSlotDialog";
import { WeeklyTemplateInput } from "@/lib/validators/scheduling";
import { Button } from "@/components/ui/button";
import { 
  AlertDialog, 
  AlertDialogAction, 
  AlertDialogCancel, 
  AlertDialogContent, 
  AlertDialogDescription, 
  AlertDialogFooter, 
  AlertDialogHeader, 
  AlertDialogTitle, 
  AlertDialogTrigger 
} from "@/components/ui/alert-dialog";
import { autoGenerateWeeklyAction } from "@/actions/schedule-generate";
import { publishTemplateToSchedule } from "@/actions/schedule-publish";
import { getCurrentSemester } from "@/actions/scheduling-data";
import { toast } from "sonner";
import { Loader2, Play, Send } from "lucide-react";

export type EntityType = "rooms" | "teachers" | "classes";

export function ScheduleManager() {
  const t = useTranslations("Admin");
  const [activeTab, setActiveTab] = useState<EntityType>("rooms");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [dialogData, setDialogData] = useState<Partial<WeeklyTemplateInput> | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);

  const [semesterId, setSemesterId] = useState<number | null>(null);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    getCurrentSemester().then(s => {
      if (s) setSemesterId(s.id);
    });
  }, []);

  const handleTabChange = (value: string) => {
    setActiveTab(value as EntityType);
    setSelectedId(null); // Reset selection when switching tabs
  };

  const handleCellClick = (dayIndex: number, period: number) => {
    // dayIndex is 0-6 (Mon-Sun), we need to map to DB Sunday-start (0=Sun, 1=Mon...)
    const dbDayOfWeek = (dayIndex + 1) % 7;
    
    setDialogData({
      dayOfWeek: dbDayOfWeek,
      startPeriod: period,
      endPeriod: Math.min(period + 1, 15),
      roomId: activeTab === "rooms" && selectedId ? parseInt(selectedId) : undefined,
      courseClassId: activeTab === "classes" && selectedId ? selectedId : undefined,
    });
    setIsDialogOpen(true);
  };

  const handleAssignmentClick = (assignment: any) => {
    setDialogData({
      id: assignment.id,
      courseClassId: assignment.courseClassId,
      roomId: assignment.roomId,
      dayOfWeek: assignment.dayOfWeek,
      startPeriod: assignment.startPeriod,
      endPeriod: assignment.endPeriod,
    });
    setIsDialogOpen(true);
  };

  const handleSuccess = () => {
    setRefreshKey(prev => prev + 1);
  };

  const handleAutoGenerate = () => {
    if (!semesterId) return;
    startTransition(async () => {
      const result = await autoGenerateWeeklyAction(semesterId);
      if (result.success) {
        toast.success("Schedule generated successfully");
        setRefreshKey(prev => prev + 1);
      } else {
        toast.error(result.error || "Failed to generate schedule");
      }
    });
  };

  const handlePublish = () => {
    if (!semesterId) return;
    startTransition(async () => {
      const result = await publishTemplateToSchedule(semesterId);
      if (result.success) {
        toast.success("Schedule published successfully");
      } else {
        toast.error(result.error || "Failed to publish schedule");
      }
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold tracking-tight">{t("Schedule")}</h1>
        <div className="flex gap-2">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="outline" size="sm" disabled={!semesterId || isPending}>
                {isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}
                {t("AutoGenerate")}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>{t("ConfirmAutoGenerate")}</AlertDialogTitle>
                <AlertDialogDescription>
                  {t("AutoGenerateDescription")}
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>{t("Cancel")}</AlertDialogCancel>
                <AlertDialogAction onClick={handleAutoGenerate}>{t("Continue")}</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>

          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="default" size="sm" disabled={!semesterId || isPending}>
                {isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}
                {t("Publish")}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>{t("ConfirmPublish")}</AlertDialogTitle>
                <AlertDialogDescription>
                  {t("PublishDescription")}
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>{t("Cancel")}</AlertDialogCancel>
                <AlertDialogAction onClick={handlePublish}>{t("Continue")}</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>
      
      <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
        <TabsList className="grid w-full grid-cols-3 lg:w-[400px]">
          <TabsTrigger value="rooms">{t("Rooms")}</TabsTrigger>
          <TabsTrigger value="teachers">{t("Teachers")}</TabsTrigger>
          <TabsTrigger value="classes">{t("CourseClasses")}</TabsTrigger>
        </TabsList>
        
        <div className="flex flex-col lg:flex-row gap-6 mt-6 min-h-[600px]">
          <div className="w-full lg:w-64 shrink-0">
            <EntitySidebar 
                type={activeTab} 
                onSelect={setSelectedId} 
                selectedId={selectedId} 
            />
          </div>
          <div className="flex-1">
            <TimeGrid 
                key={`${activeTab}-${selectedId}-${refreshKey}`}
                type={activeTab} 
                entityId={selectedId} 
                onCellClick={handleCellClick}
                onAssignmentClick={handleAssignmentClick}
            />
          </div>
        </div>
      </Tabs>

      <ScheduleSlotDialog
        isOpen={isDialogOpen}
        onClose={() => setIsDialogOpen(false)}
        initialData={dialogData}
        onSuccess={handleSuccess}
      />
    </div>
  );
}
